site_name: AlpinoGraph

theme:
    name: readthedocs

extra_css:
    - css/extra.css

markdown_extensions:
    - smarty

lang: ['nl']

nav:
    - 'Inleiding': 'index.md'
    - 'Overzicht van AlpinoGraph': 'interface.md'
    - 'Zoeken met AlpinoGraph': 'zoeken.md'
    - 'Receptenboek': 'recepten.md'
    - 'Alpino in AgensGraph': 'alpinoagens.md'
    - 'Hulpattributen': attributen.md
    - 'Cypher in AgensGraph': 'agensgraph.md'
    - 'Corpora': 'corpora.md'
    - 'Links': 'links.md'
