site_name: AlpinoGraph

theme:
    name: material
    language: nl
    palette:
        primary: green
    favicon: favicon.ico
    logo: favicon.png

extra_css:
    - css/extra.css

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.caret
    - pymdownx.highlight
    - pymdownx.superfences
    - toc:
        permalink: true
        toc_depth: 4

plugins:
    - search:
        lang: du

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/rug-compling/alpinograph-docs
          name: This documentation on GitHub

nav:
    - 'Inleiding': 'index.md'
    - 'Overzicht van AlpinoGraph': 'interface.md'
    - 'Zoeken met AlpinoGraph': 'zoeken.md'
    - 'Receptenboek': 'recepten.md'
    - 'Alpino in AgensGraph': 'alpinoagens.md'
    - 'Hulpattributen': attributen.md
    - 'Cypher in AgensGraph': 'agensgraph.md'
    - 'Corpora': 'corpora.md'
    - 'Links': 'links.md'
